name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test || echo "No tests"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd ~/mankathaspeices/mankatha-spices/backend

            echo "📥 Pulling latest code..."
            git reset --hard
            git pull origin main

            echo "⚙️ Loading Node via NVM..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm use 20

            echo "📦 Installing dependencies..."
            npm install

            echo "🚀 Restarting PM2..."

            pm2 describe mankatha-backend > /dev/null

            if [ $? -eq 0 ]; then
              pm2 restart mankatha-backend
            else
              pm2 start server.js --name mankatha-backend
            fi

            pm2 save

            echo "✅ Deployment completed"
